# Generated by Django 5.2.1 on 2026-06-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='الاسم (عربي)')),
                ('name_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (français)')),
                ('institution_type', models.CharField(default='ministry', max_length=100, verbose_name='نوع المؤسسة')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='الهاتف')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الرسمي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'موقع حكومي',
                'verbose_name_plural': 'المواقع الحكومية',
                'ordering': ['name_ar'],
            },
        ),
    ]
