# Generated by Django 5.2.1 on 2026-06-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentlocation',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='أوقات العمل'),
        ),
        migrations.AddField(
            model_name='governmentlocation',
            name='services',
            field=models.TextField(blank=True, verbose_name='الخدمات (كلمات مفتاحية مفصولة بفاصلة)'),
        ),
        migrations.AddField(
            model_name='governmentlocation',
            name='slug',
            field=models.CharField(blank=True, max_length=100, verbose_name='الرابط المختصر'),
        ),
    ]
