# Generated by Django 5.2.1 on 2026-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_governmentlocation_opening_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentlocation',
            name='institution_type',
            field=models.CharField(choices=[('presidency', 'رئاسة الجمهورية'), ('pm', 'الوزارة الأولى'), ('ministry', 'وزارة'), ('public_institution', 'مؤسسة عمومية'), ('university', 'جامعة'), ('hospital', 'مستشفى'), ('municipality', 'بلدية'), ('police', 'شرطة / أمن'), ('court', 'محكمة')], default='ministry', max_length=100, verbose_name='نوع المؤسسة'),
        ),
    ]
