# Generated by Django 5.2.1 on 2026-06-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_add_institution_type_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('place_type', models.CharField(choices=[('hospital', 'مستشفى'), ('police', 'مفوضية شرطة'), ('civil_protection', 'حماية مدنية'), ('pharmacy', 'صيدلية')], max_length=50, verbose_name='النوع')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_24h', models.BooleanField(default=False, verbose_name='متاح 24/24')),
                ('is_on_duty', models.BooleanField(default=False, verbose_name='مناوبة الآن')),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='أوقات العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مكان طوارئ',
                'verbose_name_plural': 'أماكن الطوارئ',
                'ordering': ['place_type', 'name'],
            },
        ),
    ]
