# Generated by Django 5.2.1 on 2026-06-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_add_emergency_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentlocation',
            name='address_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse (français)'),
        ),
        migrations.AlterField(
            model_name='governmentlocation',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان (عربي)'),
        ),
    ]
