# Generated by Django 5.2.1 on 2026-04-28 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_fr', models.CharField(blank=True, max_length=400, verbose_name='Nom (FR)')),
                ('name_ar', models.CharField(blank=True, max_length=400, verbose_name='الاسم (عربي)')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('source_type', models.CharField(choices=[('presidency', 'رئاسة الجمهورية'), ('pm', 'الوزارة الأولى / الوزير الأول'), ('ministry', 'وزارة'), ('other', 'أخرى')], default='ministry', max_length=20)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('rss_url', models.URLField(blank=True, help_text='رابط تغذية RSS/Atom', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=800, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=800)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.source')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'), models.Index(fields=['source', '-published_at'], name='news_articl_source__03dc81_idx')],
            },
        ),
    ]
