# Generated by Django 5.2.1 on 2026-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='news_url',
            field=models.URLField(blank=True, help_text='رابط صفحة الأخبار (يُستخدم عند عدم توفر RSS).', max_length=700),
        ),
    ]
