# Generated by Django 5.2.1 on 2026-05-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_source_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='نص المقال كاملاً لعرضه داخل البوابة'),
        ),
    ]
