# Generated by Django 5.2.1 on 2026-06-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('fr', 'French')], db_index=True, max_length=2),
        ),
    ]
