# Generated by Django 5.2.1 on 2026-06-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-id'], 'verbose_name': 'مقال', 'verbose_name_plural': 'المقالات'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'مصدر', 'verbose_name_plural': 'المصادر'},
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('government', 'الحكومة والسياسة'), ('economy', 'الاقتصاد والمالية'), ('education', 'التعليم'), ('health', 'الصحة'), ('security', 'الدفاع والأمن'), ('environment', 'البيئة والتنمية'), ('social', 'الشؤون الاجتماعية'), ('general', 'عام')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='fetch_method',
            field=models.CharField(blank=True, choices=[('rss', 'RSS'), ('sitemap', 'Sitemap'), ('scrape', 'Web Scraping'), ('api', 'API')], default='scrape', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='is_breaking',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, help_text='آخر مرة تم فيها جلب الأخبار', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='logo_url',
            field=models.URLField(blank=True, help_text='رابط شعار الوزارة', max_length=800),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='نص المقال كاملاً'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('presidency', 'رئاسة الجمهورية'), ('pm', 'الوزارة الأولى'), ('ministry', 'وزارة'), ('other', 'أخرى')], default='ministry', max_length=20),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', '-published_at'], name='news_articl_categor_d69a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_breaking', '-published_at'], name='news_articl_is_brea_af7876_idx'),
        ),
    ]
