# Generated by Django 5.2.1 on 2026-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_options_alter_source_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_fetch_count',
            field=models.PositiveIntegerField(default=0, help_text='عدد الأخبار التي تم جلبها في آخر مرة'),
        ),
        migrations.AddField(
            model_name='source',
            name='last_fetch_error',
            field=models.TextField(blank=True, help_text='رسالة الخطأ في آخر جلب'),
        ),
        migrations.AddField(
            model_name='source',
            name='last_fetch_status',
            field=models.CharField(blank=True, choices=[('success', 'نجاح'), ('fail', 'فشل'), ('unknown', 'غير معروف')], default='unknown', help_text='حالة آخر جلب', max_length=20),
        ),
        migrations.AddField(
            model_name='source',
            name='scrape_date_selector',
            field=models.CharField(blank=True, help_text='CSS selector للتاريخ (اختياري)', max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='scrape_link_selector',
            field=models.CharField(blank=True, help_text='CSS selector لعناوين المقالات (مثال: h3.node__title a)', max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='scrape_title_selector',
            field=models.CharField(blank=True, help_text='CSS selector لعنوان الخبر داخل الرابط (اختياري)', max_length=300),
        ),
    ]
