# Generated by Django 5.2.1 on 2026-06-18 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_add_scrape_config_and_fetch_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('fr', 'French')], default='ar', max_length=2)),
                ('newsletter_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('breaking', 'عاجل')], default='daily', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مشترك',
                'verbose_name_plural': 'المشتركون',
                'ordering': ['-created_at'],
            },
        ),
    ]
