# Generated by Django 5.2.1 on 2026-06-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='interests',
            field=models.JSONField(blank=True, default=list, verbose_name='الاهتمامات (slug)'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='receive_all',
            field=models.BooleanField(default=True, verbose_name='استقبال كل الأخبار'),
        ),
    ]
