# Generated by Django 5.2.1 on 2026-06-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_subscriber_interests_subscriber_receive_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر إرسال'),
        ),
    ]
