# Generated by Django 5.2.1 on 2026-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_add_last_sent_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('government', 'الحكومة والسياسة'), ('economy', 'الاقتصاد والمالية'), ('education', 'التعليم'), ('health', 'الصحة'), ('security', 'الدفاع والأمن'), ('environment', 'البيئة والتنمية'), ('transport', 'النقل'), ('energy', 'الطاقة'), ('agriculture', 'الزراعة'), ('justice', 'العدل'), ('foreign_affairs', 'الشؤون الخارجية'), ('social', 'الشؤون الاجتماعية'), ('general', 'عام')], db_index=True, default='general', max_length=20),
        ),
    ]
