# Generated by Django 5.2.15 on 2026-06-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_add_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='newsletter_type',
            field=models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('breaking', 'عاجل')], default='daily', max_length=10),
        ),
    ]
